### ISSUE TITLE
Color not reset when colored string is truncated

### ISSUE THREAD

**Issue by meribold** [arp242/elles#4]
Here's what `elles -lw34 /` looks like on my system:

![](https://github.com/arp242/elles/assets/3041190/cc43b8b0-97f6-44dc-9aea-4626f15e8cc2)

When the end of a colored string is replaced with an ellipsis, the color remains active in the next line. I tried it in a few different terminal emulators and always got the same behavior.

```
$ elles --version
elles v0.1.0 3b9afba1 2024-06-13; go1.22.4 linux/amd64; race=false; cgo=false
```

**Comment by arp242** [comment]
> I tried it in a few different terminal emulators and always got the same behavior.

I don't think there's anything that should behave different on different terminals, FYI.
